# .github/workflows/update-readme.yml
name: Update profile README
on:
  schedule:
    - cron: "15 5 * * *"   # once daily at 05:15 UTC
  workflow_dispatch:        # allow manual runs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate README content
        run: python scripts/update_readme.py
      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "chore: refresh profile README" || echo "no changes"
          git push
