name: Weekly progress issue
on:
  schedule:
    - cron: "0 15 * * MON"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  weekly-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create weekly issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GH_ME_TOKEN }}
          title: "Weekly progress – ${{ steps.date.outputs.today }}"
          content-filepath: .github/ISSUE_TEMPLATE/weekly.md
          labels: weekly, tracking
